# Generated by Django 4.2.21 on 2025-05-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing', '0002_clothingmodel_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clothing.clothingmodel')),
            ],
        ),
    ]
