# Generated by Django 4.2.21 on 2025-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingmodel',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
