# Generated by Django 4.2.21 on 2025-05-15 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothingmodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
